In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Weather.csv')
X = dataset.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y = dataset.iloc[:,-1].values

In [3]:
dataset.shape

(145460, 23)

In [4]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [5]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [6]:
#Converting 1D list to 2D list
Y = Y.reshape(-1,1)

In [7]:
#Handling nan values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
X = imputer.fit_transform(X)
Y = imputer.fit_transform(Y)

In [8]:
print(X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 20.0 ... 15.0 20.9 'No']]


In [9]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [10]:
#Handling String Data by Encoding
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [11]:
print(X)

[[2 13.4 22.9 ... 16.9 21.8 0]
 [2 7.4 25.1 ... 17.2 24.3 0]
 [2 12.9 25.7 ... 21.0 23.2 0]
 ...
 [41 5.4 26.9 ... 12.5 26.1 0]
 [41 7.8 27.0 ... 15.1 26.0 0]
 [41 14.9 20.0 ... 15.0 20.9 0]]


In [12]:
print(Y)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [13]:
Y = np.array(Y,dtype=float)
print(Y)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [14]:
#Feature Scaling b/w -3 to +3
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [15]:
print(X)

[[-1.53166617  0.19132753 -0.04135977 ... -0.01407077  0.02310362
  -0.52979545]
 [-1.53166617 -0.75105231  0.26874452 ...  0.03244663  0.387799
  -0.52979545]
 [-1.53166617  0.11279588  0.35331842 ...  0.62166712  0.22733303
  -0.52979545]
 ...
 [ 1.20928479 -1.06517892  0.52246622 ... -0.69632607  0.65037966
  -0.52979545]
 [ 1.20928479 -0.68822699  0.53656187 ... -0.29317521  0.63579185
  -0.52979545]
 [ 1.20928479  0.42692249 -0.45013361 ... -0.30868102 -0.10818671
  -0.52979545]]


In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=0)

In [17]:
print(X_train)

[[-0.75857743  1.7619606   1.35410955 ...  1.86213129  1.42353385
  -0.52979545]
 [-1.46138537 -1.81908279 -0.28098582 ... -1.06846532 -0.22488923
  -0.52979545]
 [-1.39110458  0.96093773  0.24055322 ...  0.38908008  0.32944774
  -0.52979545]
 ...
 [ 1.0687232   0.75675544  0.93124006 ...  1.10234698  1.07342629
  -0.52979545]
 [ 0.57675765 -0.04426743 -0.16822062 ...  0.01694083 -0.28324049
   1.88752093]
 [ 1.63096955 -0.0285611  -0.91529006 ... -0.35519842 -0.76463838
  -0.52979545]]


In [18]:
print(Y_train)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=175,random_state=0)
classifier.fit(X_train,Y_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(n_estimators=175, random_state=0)

In [20]:
classifier.score(X_train,Y_train)

0.9999508946985917

In [21]:
y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:153: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
print(y_pred)

['No' 'No' 'No' ... 'No' 'No' 'Yes']


In [23]:
print(Y_test)

['Yes' 'Yes' 'No' ... 'No' 'No' 'No']


In [24]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [25]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])

In [26]:
print(dataframe)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No               Yes
4                    No                No
...                 ...               ...
43633                No                No
43634                No                No
43635                No                No
43636                No                No
43637                No               Yes

[43638 rows x 2 columns]


In [27]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print('matrix',confusion_matrix(Y_test,y_pred))

print('acc',accuracy_score(Y_test,y_pred))

print('f1',classification_report(Y_test,y_pred))

matrix [[32533  1565]
 [ 4791  4749]]
acc 0.8543471286493424
f1               precision    recall  f1-score   support

          No       0.87      0.95      0.91     34098
         Yes       0.75      0.50      0.60      9540

    accuracy                           0.85     43638
   macro avg       0.81      0.73      0.76     43638
weighted avg       0.85      0.85      0.84     43638



In [28]:
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings('ignore')

In [29]:
lg = LogisticRegression()
lg.fit(X_train, Y_train)

LogisticRegression()

In [36]:
lg.score(X_train,Y_train)

0.8416845082595117

In [30]:
ypred = le6.inverse_transform(np.array(lg.predict(X_test),dtype=int))
ypred=ypred.reshape(-1,1)

In [31]:
print(ypred)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['Yes']]


In [32]:
print(Y_test)

[['Yes']
 ['Yes']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


In [33]:
df1 = np.concatenate((Y_test,ypred),axis=1)
dataf = pd.DataFrame(df1,columns=['Rain on Tommorrow','Predition of Rain'])

In [34]:
print(dataf)

      Rain on Tommorrow Predition of Rain
0                   Yes                No
1                   Yes                No
2                    No                No
3                    No                No
4                    No                No
...                 ...               ...
43633                No                No
43634                No                No
43635                No                No
43636                No                No
43637                No               Yes

[43638 rows x 2 columns]


In [35]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_score
print('confusion matrix')
print(confusion_matrix(Y_test,ypred))
print('accuracy',accuracy_score(Y_test,ypred))

confusion matrix
[[32362  1736]
 [ 5132  4408]]
accuracy 0.8426142352995096
